version: '2'
services:
  btc:
    image: bitcoind
    build:
      context: bitcoind/
    volumes:
      - bitcoin:/bitcoin/.bitcoin
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - BITCOIN_DATA

  bitcoind:
    extends: btc
    container_name: bitcoind
    entrypoint: ["./start-bitcoind.sh"]

  bitcoin-cli:
    extends: btc
    container_name: bitcoin-cli
    entrypoint: ["./start-bitcoin-cli.sh"]
    links:
      - "bitcoind:rpcserver"

  lnd:
    image: lnd
    container_name: lnd
    build:
      context: lnd/
    environment:
      - RPCUSER
      - RPCPASS
      - NETWORK
      - DEBUG
    entrypoint: ["./start-lnd.sh"]
    links:
      - "bitcoind:blockchain"

volumes:
  bitcoin:
    driver: local
